FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN ls

ARG VITE_MATHLLM_BACKEND_ADDRESS
ARG VITE_LLMATH_PROBLEMS_API_URL

ENV VITE_MATHLLM_BACKEND_ADDRESS=$VITE_MATHLLM_BACKEND_ADDRESS
ENV VITE_LLMATH_PROBLEMS_API_URL=$VITE_LLMATH_PROBLEMS_API_URL

RUN npm run build

RUN npm install -g serve

EXPOSE 3000
CMD [ "serve", "-s", "dist" ]